services:
  python:
    build:
      context: .
      target: production
    volumes:
      - type: bind
        source: ./App
        target: /home/
    entrypoint: python /home/manage.py runserver 0.0.0.0:8000

    ports:
      - target: 8000
        published: 8000
